### ISSUE TITLE
arc_padding not found

### ISSUE THREAD

**Issue by Anandsoni14** [florent37/ArcLayout#11]
Error:/Location/app/src/main/res/layout/app_bar_main.xml:24 attribute 'package_name:arc_padding' not found
Error:java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by yuwu** [comment]
+1

**Comment by MahdiHatami** [comment]
same issue

**Comment by Hitexroid** [comment]
+1

**Comment by Hitexroid** [comment]
remove `app:arc_padding="30dp"`

**Comment by Anandsoni14** [comment]
Already tried. But doesn't work.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On Wed, Oct 4, 2017 at 12:30 AM, Sadeq <notifications@github.com> wrote:

> remove app:arc_padding="30dp"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/02d846d6c92a767a53fada0d9e6c8e29494d8c11?url=https%3A%2F%2Fgithub.com%2Fflorent37%2FArcLayout%2Fissues%2F11%23issuecomment-333944636&userId=1015939&signature=25e222543d97a82d>,
> or mute the thread
> <https://mailtrack.io/trace/link/4a2ba4add11cb89095b5b5adbceaa6d328f76bfd?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJJE0cYYwviMPF1FUW9GgcfQkfBBnpMAks5sooQ6gaJpZM4OQOvr&userId=1015939&signature=25f987ce1ccbc8bf>
> .
>



--
