### ISSUE TITLE
Arclayout not working Android 9

### ISSUE THREAD

**Issue by vipulasri** [florent37/ArcLayout#18]
Arclayout not working on Android Pie.

OS: Android 9.0

Device: Pixel 2 XL 

![screenshot](https://i.imgur.com/QDzJUhy.jpg)

**Comment by florent37** [comment]
I'm working on it


Le ven. 10 août 2018 à 07:42, Vipul Asri <notifications@github.com> a
écrit :

**Comment by vipulasri** [comment]
@florent37 what can be the issue? I don't see any error logs for this.

**Comment by florent37** [comment]
They changed the low level renderer. Romain Guy sent me soleil possible
fixes

Le ven. 10 août 2018 à 09:39, Vipul Asri <notifications@github.com> a
écrit :

**Comment by vipulasri** [comment]
Do share the insights what he shared and reason behind it.

**Comment by florent37** [comment]
It was on a french slack ''android dev fr''

Le ven. 10 août 2018 à 11:10, Vipul Asri <notifications@github.com> a
écrit :

**Comment by vipulasri** [comment]
Can you share his post here or give me the link to that. As I am not in that group and don't seem find the invite to that group publically.

**Comment by florent37** [comment]
https://join.slack.com/t/android-dev-france/shared_invite/enQtMjc2NDA3Nzg4NDIxLTNhMGRiOWMwN2MyNDVhMzVmZDNjMWE5NjdlYjlkYWY4ZWNhODkwYWQ0Y2Y0ZDM5OGM3NmQ0MjYxMDVkNTdkMGM

**Comment by florent37** [comment]
I fixed the same bug on ShapeOfView

you can use this lib instead : https://github.com/florent37/ShapeOfView

it allow to draw arcs too

**Comment by florent37** [comment]
fixed on the 1.0.4
