### ISSUE TITLE
Arc not drawing on android Pie

### ISSUE THREAD

**Issue by rahulr4** [florent37/ArcLayout#19]
Hie,
Please make your third party compatible with android Pie. I just checked it on pie and the arc is not rendering

**Comment by rahulr4** [comment]
![device-2018-09-11-151847](https://user-images.githubusercontent.com/3830891/45352382-00738680-b5d6-11e8-9214-13e0fb2fe842.png)

**Comment by florent37** [comment]
I know this bug, please try with https://github.com/florent37/ShapeOfView

I fixed his bug on this other lib

**Comment by florent37** [comment]
fixed on the 1.0.4
