### ISSUE TITLE
Arc does not show in android 9

### ISSUE THREAD

**Issue by janmylermedia** [florent37/ArcLayout#20]
tested the library on my oneplus 6, the arc didn't show

**Comment by primus-anonymous** [comment]
Having the same issue

**Comment by meloveself94** [comment]
same.. tested on oneplus 6 android P as well.. arc doesn't show

**Comment by babyofish** [comment]
me too。。。

**Comment by Destiny01** [comment]
me too

**Comment by babyofish** [comment]
It works well in android 9.0 with using the aar in the source of demo instead of "compile 'com.github.florent37:arclayout:1.0.3'".

**Comment by Gamis214** [comment]
I have the same issue :( how fix this ?

**Comment by raghavsatyadev** [comment]
@florent37  has to add proguard nothing else

**Comment by florent37** [comment]
It's a proguard issue ?

Le dim. 2 déc. 2018 à 08:07, Raghav Satyadev <notifications@github.com> a
écrit :

**Comment by raghavsatyadev** [comment]
Yes and no florent, I have forked your repo and made my own one because of some urgency , you can check it on emulator. I think the reason was that your library has old version code and repo has new one. The repo code works on Android Pie.

https://bintray.com/raghavsatyadev/Maven/ArcLayout/1.0.0

Please add this in project level gradle, I am currently waiting for it to add on Jcenter, so.

repositories {
    maven {
        url  "https://dl.bintray.com/raghavsatyadev/Maven" 
    }
}

**Comment by florent37** [comment]
@raghavsatyadev can you send me the modified code ?

**Comment by raghavsatyadev** [comment]
It is in my repo : https://github.com/raghavsatyadev/ArcLayout

**Comment by florent37** [comment]
I published a 1.0.5, can you try it ?

**Comment by florent37** [comment]
I tested on a OnePlus 6T : Android 9 and it works

**Comment by raghavsatyadev** [comment]
yep it works

**Comment by AzimLord** [comment]
<a href="https://imgur.com/u7D3PXg"><img src="https://i.imgur.com/u7D3PXg.png" title="source: imgur.com" /></a>

Not working for me version 1.0.5

**Comment by AzimLord** [comment]
> [![](https://camo.githubusercontent.com/4fc9a6b9a38a6197d7b3d6b9e3c5214c48fdc345/68747470733a2f2f692e696d6775722e636f6d2f753744335058672e706e67)](https://imgur.com/u7D3PXg)
> 
> Not working for me version 1.0.5

Well then, I need to add `app:arc_position="bottom`. My mistake

**Comment by florent37** [comment]
can you try with https://github.com/florent37/ShapeOfView ?
