### ISSUE TITLE
Wrong cropDirection values 

### ISSUE THREAD

**Issue by romtsn** [florent37/ArcLayout#6]
Hey, so the bug: in the `attrs.xml` you have next values (0 and 1) for `arc_cropDirection` attribute
```xml
<attr name="arc_cropDirection" format="enum">
    <enum name="cropInside" value="0" />
    <enum name="cropOutside" value="1"/>
</attr>
```
But in the `ArcLayoutSettings` there are other values (1 and 2) for `CROP_INSIDE` and `CROP_OUTSIDE` respectively
```java
public class ArcLayoutSettings {
    public final static int CROP_INSIDE = 1;
    public final static int CROP_OUTSIDE = 2;
    ...
}
```

So, therefore your `isCropInside()` method will always return `true`, which is wrong, cause you calculate it like 
```java
cropInside = (cropDirection & CROP_INSIDE) == CROP_INSIDE;
```

**Comment by florent37** [comment]
yes fixed ;)
