### ISSUE TITLE
Shadow not appearing

### ISSUE THREAD

**Issue by shinayser** [florent37/ArcLayout#7]
Hey man thanks for such awesome library!

My issue is: when using the **cropOutside** example the shadow is not being shown below the arc layout. Is there something I am missing?

Thanks again!

**Comment by shinayser** [comment]
Just found out tat the example had not an "elevation" tag. Pehaps adding it to the README will prevent future problems for other users =)

**Comment by florent37** [comment]
done ;)

2017-02-23 16:13 GMT+01:00 shinayser <notifications@github.com>:
