### ISSUE TITLE
Anti-aliasing?

### ISSUE THREAD

**Issue by shinayser** [florent37/ArcLayout#8]
Awesome library dude!

But unfortunatly, some devices get it's arc very pixalized. There is any kind of anti-aliasing our any good practice that I am missing ?

Thanks a lot!

**Comment by tinyxdy** [comment]
@Override
    protected void dispatchDraw(Canvas canvas) {
        paint.setAntiAlias(true);
        paint.setColor(Color.WHITE);
        int saveCount = canvas.saveLayer(0, 0, getWidth(), getHeight(), null, Canvas.ALL_SAVE_FLAG);
        super.dispatchDraw(canvas);
        paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.MULTIPLY));
        canvas.drawPath(clipPath, paint);
        canvas.restoreToCount(saveCount);
        paint.setXfermode(null);
    }

**Comment by LT5505** [comment]
Thank you every much.
